apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: default
  namespace: opentelemetry
spec:
  mode: deployment
  ports:
    - name: otlp-grpc
      port: 4317
      appProtocol: grpc
  config: |
    ---
    # RECEIVERS (inputs)
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${MY_POD_IP}:4317

    # PROCESSORS
    processors:
      resource:
        attributes:
          - action: insert
            key: loki.resource.labels
            value: service.name
      transform/span_name:
        trace_statements:
          - context: span
            statements:
              - set(attributes["span.name"], name)      
      spanmetrics:
        metrics_exporter: prometheusremotewrite # важно!
        latency_histogram_buckets: [50ms, 100ms, 150ms, 200ms, 250ms, 300ms, 350ms, 400ms, 450ms, 500ms]
        dimensions:
          - name: span.name
          - name: http.method
          - name: http.route
          - name: http.status_code
        dimensions_cache_size: 1000

    # EXPORTERS (output)
    exporters:
      logging:
        verbosity: detailed
      loki:
        endpoint: http://loki.grafana:3100/loki/api/v1/push
        tls:
          insecure: true
      otlp/tempo:
        endpoint: http://tempo.grafana:4317
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: http://promstack-prometheus.prometheus:9090

    # EXTENSIONS
    extensions:
      health_check:
        endpoint: ${MY_POD_IP}:13133

    # MAIN CONFIG
    service:
      extensions:
        - health_check
      pipelines:
        logs:
          receivers:
          - otlp
          processors:
          - resource
          exporters:
          - loki
        metrics:
          receivers:
          - otlp
          exporters:
          - prometheusremotewrite
        traces:
          receivers:
          - otlp
          processors:
          - transform/span_name
          - spanmetrics
          exporters:
          - otlp/tempo