ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: minikube-ca
  hosts: [grafana.test]
  # tls: [{hosts: [grafana.test, secretName: grafana-cert}]
persistence:
  type: pvc
  enabled: true
